name: mtflow

volumes:
  unitycatalog_data:

services:
  unitycatalog:
    container_name: mt-unitycatalog
    image: unitycatalog/unitycatalog:v0.2.1
    ports:
      - "${UC_PORT:-8080}:8080"
    volumes:
      - ./etc/conf:/opt/unitycatalog/etc/conf
      - unitycatalog_data:/opt/unitycatalog/etc/data
    profiles:
      - unitycatalog
